### PR TITLE
Milestone 2: User interface

### PR DESCRIPTION
**Pull request by SarvarKh**
## Tic-Tac-Toe game milestone 2: User interface
In this milestone we:

- created user_interface branch from dev-branch;
- added game interactive sections like: 
> welcome, user inputs, game rules, start-game, winning combination, end game or restart;

### CODE REVIEW

**Comment by PhillipUg** [comment]
# Invalid Submission 🔴 

- [ ] Your project is not working. I think this is mainly you're missing the `.rb` file extension on your `main` file in the `bin` folder. Also, you need to comment the first line in your `main.rb` file.

**Friendly reminder:** You should submit a working project. If you cannot fix it by yourself, reach out to a full-time TSE. [This article](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-) describes how to set up a meeting with full-time TSEs.  
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

For any assistance feel free to reach out to me on slack as **Phillip Musiime**

**Comment by SarvarKh** [comment]
### Hey Phillip. Thank you for your prompt review.
I will implement your comment.

**Before that, may I clarify one point:**
The reason why ruby file didn't contain an extension ".rb" is because in the Microverse path there was an instruction to make ruby file executable.
If you refer to this article given by Microverse as project requirement, it requests to change main.rb to main itself.
[Projec requirement in milestone 1](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/)

I also attached snapshot highlighting specifically this request in this article.

Untitled

- [ ] _If you could support me why this requirement was given or where I did something wrong, I'd appreciate._

**Comment by SarvarKh** [comment]
Thanks @PhillipUg  for your support and showing me the reason of failure in code via slack.
_I remained the ruby file as "main" without changing it to "main.rb" since it was a [Project requirement in milestone 1](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/)_

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
### Hi @SarvarKh ! 👋 👋 

#### You have done well so far :clap: However, there are changes required for you to make for this milestone to be approved. Kindly work on them and submit them for another code review.

**Recommended**

- [ ] Game tells which player turn it is (without computing who the winner is). Currently, your game computes the winner after both players play once.

- [ ] Game asks the player to select from available moves.

- [ ] Game informs player if the selected move is invalid (without computing what an invalid move is).

- [ ] Game displays board after the player move.

- [ ] Game informs the player if the selected move is a draw move.

- [ ] Game repeats all actions for the next player's move.
Instead of repeating the player turns manually, identify the steps taken in each turn, (ask the player for input, check if its valid, display board, etc ) and repeat those steps within a while loop until the game is won or a draw is reached. It doesn't have to function completely, but you have to show that you have thought of it this way.

- [ ] Fix your rubocop errors. It can be fixed with `rubocop -a`

**Optional**

- [ ]  Check that the player's name can't be left blank.

- [ ] The game should restart when asked if the players want to play again.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this milestone approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
